var name, email, fullName;


document.write("<h1>Rules For Naming JS Variables</h1>");
document.write(
  "Variable names can only contain , numbers , $ and _. For Example: @my_1variable <br>"
);
document.write(
  "Variable must begin with a , letter , @ or _. For Example: variable, @variable, _variable <br>"
);
document.write("Variable names are case sensitive <br>");
document.write("Variable names should not be JS keywords <br>");